ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName		= "Laser Projectile"
ENT.Author			= "Paradukes"

ENT.Spawnable		= false
ENT.AdminSpawnable	= false
ENT.follow			= nil
ENT.Owner			= nil
ENT.Exploded		= false
ENT.FuelAmount		= 1000000
ENT.LastPosition		= Vector(0,0,0)
ENT.XCo			= nil
ENT.YCo			= nil
ENT.ZCo			= nil
ENT.Target			= Vector(0,0,0)
ENT.PhysObj			= nil
ENT.Locked			= false
ENT.PreLaunch		= false
ENT.STime			= nil
ENT.LTime			= nil
ENT.ParL			= nil
